/** Supplies a virtual content manifest and regenerates typed output for repository builds. */
import path from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import matter from "gray-matter";
import { normalizePath, type Plugin, type ViteDevServer } from "vite";
import { DocumentFileScanner } from "../filesystem/DocumentFileScanner";
export class DocumentManifestPlugin {
  constructor(private readonly docsDir = "docs", private readonly writeManifest = true) {}
  plugin(): Plugin {
    const docsDir = this.docsDir;
    const writeManifest = this.writeManifest;
    let root = "";
    let docsRoot = "";
    let virtualSource = "";
    let timer: ReturnType<typeof setTimeout> | undefined;
    let pending = Promise.resolve();
    const virtualId = "\0virtual:rdocser/documents";
    const generate = () => {
      pending = pending.catch(() => {}).then(async () => {
        const documents = await new DocumentFileScanner().scanDocuments(docsRoot);
        const runtimeImports = documents.map(doc => `  ${JSON.stringify(doc.id)}: () => import(${JSON.stringify(normalizePath(path.join(docsRoot, doc.sourcePath)))}),`).join("\n");
        virtualSource = `export const documentManifest = ${JSON.stringify(documents)};\nexport const documentLoaders = {\n${runtimeImports}\n};\n`;
        if (!writeManifest) return;
        const destination = path.join(root, "src/generated/document-manifest.ts");
        const imports = documents.map(doc => {
          let relative = normalizePath(path.relative(path.dirname(destination), path.join(docsRoot, doc.sourcePath)));
          if (!relative.startsWith(".")) relative = `./${relative}`;
          return `  ${JSON.stringify(doc.id)}: () => import(${JSON.stringify(relative)}),`;
        }).join("\n");
        const source = `/** Generated by DocumentManifestPlugin. Do not edit. */\nimport type { DocumentManifestEntry } from "../domain/documents/DocumentManifest";\nexport type { DocumentManifestEntry } from "../domain/documents/DocumentManifest";\nexport const documentManifest: DocumentManifestEntry[] = ${JSON.stringify(documents, null, 2)};\nexport const documentLoaders = {\n${imports}\n};\n`;
        await mkdir(path.dirname(destination), { recursive: true });
        const previous = await readFile(destination, "utf8").catch(() => "");
        if (previous !== source) await writeFile(destination, source, "utf8");
      });
      return pending;
    };
    const watch = (server: ViteDevServer) => {
      server.watcher.add(docsRoot);
      const changed = (_event: string, filename: string) => {
        const relative = path.relative(docsRoot, filename);
        if (relative.startsWith("..") || path.isAbsolute(relative) || !/\.(md|mdx)$/i.test(filename)) return;
        clearTimeout(timer);
        timer = setTimeout(() => { void generate().then(() => {
          const module = server.moduleGraph.getModuleById(virtualId);
          if (module) server.moduleGraph.invalidateModule(module);
          server.ws.send({ type: "full-reload" });
        }).catch(error => {
          server.config.logger.error(String(error));
          server.ws.send({ type: "error", err: { message: String(error), stack: "", plugin: "rdocser-documents" } });
        }); }, 100);
      };
      server.watcher.on("all", changed);
      server.httpServer?.once("close", () => { clearTimeout(timer); server.watcher.off("all", changed); });
    };
    return {
      name: "rdocser-documents", enforce: "pre",
      configResolved(config) { root = config.root; docsRoot = path.resolve(root, docsDir); },
      buildStart: generate, configureServer: watch,
      resolveId(id) { if (id === "virtual:rdocser/documents") return virtualId; },
      load(id) { if (id === virtualId) return virtualSource; },
      transform(code, id) { if (/\.(md|mdx)$/i.test(id)) return { code: matter(code).content, map: null }; },
    };
  }
}
